version: '1'

services:
  app:
    image: 'superhero:latest'
    build:
      context: .
      container_name: app
      depends_on:
        - db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=asdf1234
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
      ports:
        - '8080:8080'

  db:
    image: 'postgres:18-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf1234
      - POSTGRES_DB=rest
    ports:
      - '5432:5432'
